### ISSUE TITLE
(Very) large random increase of steps between 3-5am

### ISSUE THREAD

**Issue by mrpotatocode** [SecUSo/privacy-friendly-pedometer#104]
Hi there, 

Three or four times now, my pedometer has added a huge amount of steps to my pedometer between 3 and 5am (it's always between these times, see screenshots.) I'm not using the phone at that time (asleep), and no obvious changes to the phone (e.g. battery didn't die, no phone updates, etc). I can't edit the steps due to Issue #101 (which I read has an upcoming resolution, thank you!) Android version 12, Samsung Galaxy S10e. 

![Day Image](https://user-images.githubusercontent.com/68235853/175695757-1a368142-8276-4cd8-aef9-f8256179ed57.jpeg)
![Another Day Image](https://user-images.githubusercontent.com/68235853/175696206-44d0d8ca-36ea-43d0-a9ea-2c5ef3bc1bb7.jpeg)
![Third Day Image](https://user-images.githubusercontent.com/68235853/175696209-8cc542fe-1d6e-4bd9-94d4-847b08bd65f5.jpeg)

![A Week View](https://user-images.githubusercontent.com/68235853/175695763-1134cf9d-b37b-429c-8ce6-f50a79460ed8.jpeg)

**Comment by q-wertz** [comment]
Same issue for me since the update. The counter updates life but the graphs seem to be off.

**Comment by sleep-yearning** [comment]
Please let us know if this occurs with 3.0.1 still. :)

**Comment by mrpotatocode** [comment]
Have had no issues with 3.0.1! Should be safe to close. Thanks for your work!
