### ISSUE TITLE
Step counter doesn't reset after day end

### ISSUE THREAD

**Issue by Huy-Ngo** [SecUSo/privacy-friendly-pedometer#109]
### Issue

Since the app was updated a few days ago, the step counter doesn't reset after the day has ended. As a result, the number is very large even though I haven't walked much during the day:

![Pedometer daily step count saying 11386 steps, but the hourly graph doesn't show any step changes](https://user-images.githubusercontent.com/19296926/190880205-b2301d39-ffc0-49be-9bf3-cf01be7dbaef.jpg)

In the weekly and monthly graphs, the previous days are also shown as 0, while the last day is their sum:

![Pedometer step count showing day 16.09 and 17.09 I haven't walked a single step, but on 18.09 I have walked 11386 steps](https://user-images.githubusercontent.com/19296926/190880232-fdd7f27a-a9ed-4468-b63a-0ef713aa5de1.jpg)

### System information

- Android version: 10
- App version: 3.0.0

**Comment by q-wertz** [comment]
Same issue on NokiaX20, Android 12

Also tried to use the hardware counters, same issue.

**Comment by nahkoots** [comment]
Same issue on Galaxy S4, Android 11, app version 3.0.0.

**Comment by Huy-Ngo** [comment]
It also seems that it doesn't register the step count for the current day. I had quite a walk today and the total step count does increase a lot, but the graph doesn't show anything.

**Comment by alex1701c** [comment]
I have the same issue.

@sleep-yearning Any chance you could look into this?

**Comment by urza9814** [comment]
Just adding one more report -- same issue here on a OnePlus 6 running LineageOS, app version 3.0.0, Android 11

**Comment by Huy-Ngo** [comment]
anyone knows if this bug occurs on any version <3.0.0?

**Comment by q-wertz** [comment]
Before 3.0.0 it worked well for me

**Comment by alex1701c** [comment]
I downgraded the app and it fixed the issue.

**Comment by Huy-Ngo** [comment]
I also couldn't downgrade, due to unknown error as well (running stock ROM) :cry:

**Comment by alex1701c** [comment]
I remember having issues downgrading as well, but I uninstalled the old version first and then installed the older version from F-Droid.

**Comment by alex1701c** [comment]
@Kamuno Could you look into this?

**Comment by goedl** [comment]
Same here.
Also I can not downgrade: unknown error
I'm hesitant to uninstall and reinstall. I guess the databse will not survive this, right?
And exporting data still shows incorrect dates. I guess this fix https://github.com/SecUSo/privacy-friendly-pedometer/pull/94 has not been applied so far, right?
And if export would work I would not be able to import it back anyway, right?

**Comment by alex1701c** [comment]
@Kamuno @sleep-yearning Any chance you cool look into this? I really like this app and think it's unfortunate that the only solution is a downgrade :/

**Comment by goedl** [comment]
Eureka!
Latest update (3.0.1.) finally made the programm work again.
Even the faulty export seems to be fixed. Thanx.
