### ISSUE TITLE
Add default text to notification if nothing is chosen

### ISSUE THREAD

**Issue by jeisoncp** [SecUSo/privacy-friendly-pedometer#11]
I want to suggest hide the notification if none info is shown in it.

<p><img src="https://cloud.githubusercontent.com/assets/7952798/20242283/49422e90-a910-11e6-970a-40d5c029dc8d.png" height="400px"></p>

I know that notification is called "Permanent Notification" because it is permanent, but it bores me. I tried disable the background step count, but it continues in my status bar.

**Comment by tobiasneidig** [comment]
The notification is required by android if a service runs in background. To remove the notification, you either have to disable the background step counter or long-press the notification, press the info-icon and choose "block all" in system settings. Be aware that the last solution will also prevent the app from displaying the motivation alert.

**Comment by jeisoncp** [comment]
After reboot the system, the notification disappeared. Sorry for not letting you know before.

**Comment by Yonjuni** [comment]
I would suggest to add some message to the notification in case nothing is displayed. 
And add the switch to turn off the app from https://github.com/SecUSo/privacy-friendly-activity-tracker/issues/6

**Comment by Yonjuni** [comment]
Integrated in next update.
