### ISSUE TITLE
Removed from F-Droid?

### ISSUE THREAD

**Issue by locness3** [SecUSo/privacy-friendly-pedometer#113]
I can not find this app on F-Droid anymore. The link in the README goes to a 404 page. What happened?

**Comment by locness3** [comment]
Yes, I now see the mention in the README. Is there any third-party initiative to maintain this app?

**Comment by morckx** [comment]
> Yes, I now see the mention in the README. Is there any third-party initiative to maintain this app?

I have offered my help with maintenance, code review and answering questions. We had a meeting last week and chances are good that the pedometer will survive.

**Comment by Fijxu** [comment]
I have used a lot this app, pretty good and simple. I think it doesn't need any updates because it already serves the main purpose, but if someone wants to maintain and update it, it will be good

**Comment by IzzySoft** [comment]
@morckx once things are settled and the path is clear, just give us a ping. Currently, the app is archived at F-Droid; as everything is set up already it's a one-liner in the YAML file to bring it back to the main repo. So if the app shall be restored, that can be achieved easily (I'd volunteer to do that then so pinging me e.g. here would suffice; disclosure: I'm one of the F-Droid maintainers).

**Comment by sleep-yearning** [comment]
@IzzySoft would you be so kind and add it back to the repo? 3.0.1 was just released and should improve some issues with the step saving now.

**Comment by IzzySoft** [comment]
OK, thanks – that was successful. And provided new details to an open GitLab issue, in case you wonder why the MR looks so strange and wasn't merged: https://gitlab.com/gitlab-org/gitlab/-/issues/389074#note_1261537503
