### ISSUE TITLE
Make widget vertically resizeable

### ISSUE THREAD

**Issue by leo030303** [SecUSo/privacy-friendly-pedometer#121]
The widget can be resized horizontally but not vertically, it defaults to two rows high.
Android version 13 with Neo Launcher

**Comment by morckx** [comment]
@leo030303 : Could you please have a look, if #124 resolves your issue? It works with trebuchet, google and pixel launcher on different API (tested: 21, 33, 34).

**Comment by leo030303** [comment]
Yep, default widget size is now 1x1 on Neo launcher with API 33, thanks so much!

**Comment by morckx** [comment]
> Yep, default widget size is now 1x1 on Neo launcher with API 33, thanks so much!

Thank you for reporting, testing and suggesting a fix!
