### ISSUE TITLE
Add export data feature

### ISSUE THREAD

**Issue by jsparber** [SecUSo/privacy-friendly-pedometer#18]
Pls add a possibility to export the data collected by the app.

**Comment by frodeseverin** [comment]
I second this request.

**Comment by JonathanMM** [comment]
If we can to export data to csv, like google fit, it can be perfect and interoperable :)

**Comment by matthiasbeyer** [comment]
Hi.

I'm here to push this issue. Please add a CSV export! Right now [https://github.com/j4velin/Pedometer](https://github.com/j4velin/Pedometer) is superior because of its export feature. This app has more features than the Pedometer of @j4velin, but the export functionality is a crucial feature for me, so I cannot switch.

Please consider adding the CSV export feature. If you'd prefer JSON, that's fine for me, too!

**Comment by matthiasbeyer** [comment]
Hello. I feel like this app is no longer maintained. Still pushing this, though.

**Comment by Yonjuni** [comment]
@matthiasbeyer It still is maintained. There also is an update on the way (but I can't say a date, yet). We're also working on a way to enable import/export for all Privacy Friendly Apps.

**Comment by matthiasbeyer** [comment]
Awesome, thanks!

**Comment by natrius** [comment]
Right now there is no way without titanium or something else?

**Comment by licaon-kter** [comment]
@natrius `adb backup ...` works, does not need root.

But yeah, a simple XML/database export/import would be nicer.

**Comment by matthiasbeyer** [comment]
Replace that `XML` in that sentence with `JSON` and we're talkin' :smile:

**Comment by licaon-kter** [comment]
@matthiasbeyer A plaintext file, whatever is easier to code.

**Comment by matthiasbeyer** [comment]
Seems that nothing is happening here?

**Comment by natrius** [comment]
Nah, my best guess is, they use it to teach how to develop apps. (Nice thing :) ) 
It seems like they don't teach on how to keep apps updated or how to support apps or anything like that.

**Comment by sleep-yearning** [comment]
Unfortunately, our resources are split up between a lot of apps.

**Comment by lollita** [comment]
A import function is still missing?
I cannot to use it without import my historical.
