### ISSUE TITLE
Change "cal" to either "Cal" or better "kcal"

### ISSUE THREAD

**Issue by licaon-kter** [SecUSo/privacy-friendly-pedometer#21]
Else you'll walk 10km and wonder why you've spend a biscuit size calorie intake. ;)

More: https://en.wikipedia.org/wiki/Food_energy

**Comment by Yonjuni** [comment]
Closed by 1f3b422fcdb62c6e23cbff57b3e2b55977e13109

**Comment by licaon-kter** [comment]
Not fixed in 1.0.3 on F-Droid.

**Comment by Yonjuni** [comment]
Then there must have been a misunderstanding of the issue from our side. Could you explain further ;-) ?

**Comment by licaon-kter** [comment]
Umm, not fixed as in "app does not say kcal in 1.0.3 from F-Droid"

**Comment by Yonjuni** [comment]
We have updated it in the String files, I have just checked it.

**Comment by licaon-kter** [comment]
I saw it, but you missed one: https://github.com/SecUSo/privacy-friendly-pedometer/blob/master/app/src/main/res/values/strings.xml#L38 ?

**Comment by Yonjuni** [comment]
I guess so.

**Comment by un-logic** [comment]
Also, what about [notification text on caliries](https://github.com/SecUSo/privacy-friendly-pedometer/blob/master/app/src/main/res/values/strings.xml#L170)? Maybe value must be multitude of 1000, or __calories__ be replaced with __kcal__, or even deleted at all?

**Comment by licaon-kter** [comment]
Yes, saw that when I translated, forgot to raise the issue.
