### ISSUE TITLE
Android 4.4.2/ Samsung GT-N7100: Crashes on start.

### ISSUE THREAD

**Issue by Rbagman** [SecUSo/privacy-friendly-pedometer#28]
Android 4.4.2/ Samsung GT-N7100: This app gives a notice: 0 of n steps walked and crashes on start, every time. Have rebooted device and no change.

**Comment by Yonjuni** [comment]
Thanks for the comment. Could you tell me wish version of the APP.

**Comment by Yonjuni** [comment]
Fixed with https://github.com/SecUSo/privacy-friendly-pedometer/commit/252193f949651a4c6a5ead99bb219e86d51a16db
