### ISSUE TITLE
Exit Button

### ISSUE THREAD

**Issue by nlover6** [SecUSo/privacy-friendly-pedometer#31]
App Most Use From Battery, Is Good Show A Exit Button In App And When User Click In The Exit Button, App Force Stop, And All Service Is Stop.

**Comment by licaon-kter** [comment]
Also, this needs a dialogue maybe, so to make it clear that "Exiting will stop counting steps!"

**Comment by nlover6** [comment]
Yes, when user dont need to counting step, click on exit button and then stop all service and stop counting steps, to don't use battery.

**Comment by Yonjuni** [comment]
https://github.com/SecUSo/privacy-friendly-pedometer/issues/6 will cover this.

**Comment by Yonjuni** [comment]
Will be covered by #6
