### ISSUE TITLE
Save Step Bug

### ISSUE THREAD

**Issue by nlover6** [SecUSo/privacy-friendly-pedometer#32]
When i walk and step detector for example count 30 step for me, and i go setting -> general, and deactive (Permanent step counter) and back to main activity and see step count is 0 !!!!!

**Comment by Yonjuni** [comment]
This problem has been reported here: https://github.com/SecUSo/privacy-friendly-pedometer/issues/6

**Comment by Yonjuni** [comment]
Closed due to duplicate
