### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by freedentwhite** [SecUSo/privacy-friendly-pedometer#33]
How I can translate your application in French?
If I can participate :)
Thank you

**Comment by licaon-kter** [comment]
Get https://github.com/LonamiWebs/Stringlate ;)

**Comment by Yonjuni** [comment]
@freedentwhite Sure you can.

**Comment by freedentwhite** [comment]
Thanks you, I use Stringlate good and simply application. Perfect :)

**Comment by freedentwhite** [comment]
Thanks you, I use Stringlate good and simply application. Perfect :)
