### ISSUE TITLE
Manual correction of steps

### ISSUE THREAD

**Issue by Yonjuni** [SecUSo/privacy-friendly-pedometer#37]

**Comment by natrius** [comment]
That would be great because yesterday the app counted about 2.000 steps while i was sleeping. It just happened yesterday and unfortunately i cannot reproduce it. 
I'm using a oneplus 3 with slimRom Slim-6.0.1.build.2.0-STABLE-20170118-0205 nad kernel 3.18.39-Slim-g9cd353e.

**Comment by Yonjuni** [comment]
@natrius If this question is not too private: were was the phone? Was it just lying somewhere?

**Comment by natrius** [comment]
On the other side of the bed, about 1m far and on another matress. There should not be any movement there :D

**Comment by Yonjuni** [comment]
Okay thanks :D

**Comment by natrius** [comment]
Problem did not happen again, but today there was not one step counted at all. Probably my fault. From my other cellphone i know how much steps it was (somehow) and others may have an activity-wristband or something like that.
So, that feature would be really appreciated.

**Comment by Kamuno** [comment]
Graph should adjust accordingly.

**Comment by Yonjuni** [comment]
Is integrated in the next update.
