### ISSUE TITLE
Hardware step-sensor

### ISSUE THREAD

**Issue by sniperle** [SecUSo/privacy-friendly-pedometer#5]
Make use of the hardware step-sensor which is build-in modern phones, this will save battery and improve accuracy.

**Comment by tobiasneidig** [comment]
The app uses the Android hardware step detector if available. The battery usage of this sensor is not as high as using the accelerometer. In contrast to the hardware step counter the device has to be active when step detector is triggered. The usage of step counter gives the ability to improve the accuracy if devices wakes up rarely.

To implement the step counter the new service has to implement [AbstractStepDetectorService](https://github.com/SecUSo/privacy-friendly-activity-tracker/blob/master/app/src/main/java/org/secuso/privacyfriendlyactivitytracker/services/AbstractStepDetectorService.java). In addition to that a setting will be useful to let the user choose which sensor should be used.

**Comment by Yonjuni** [comment]
Integrated in next update.
