### ISSUE TITLE
Stopping background counting

### ISSUE THREAD

**Issue by SenaidaHdez** [SecUSo/privacy-friendly-pedometer#51]
I want to have background counting while in training mode but not when it is not activated. However, desactivating the option from the settings panel doesn't interrupt the program. I want to do this so it doesn't consume battery when I don't want to.

Thanks

**Comment by Yonjuni** [comment]
Belongs to https://github.com/SecUSo/privacy-friendly-pedometer/issues/6
We are currently working on it. I'll close it, because it's part of the other issue. But @SenaidaHdez Thanks for reporting :)
