### ISSUE TITLE
Step Count is not updating when app opens

### ISSUE THREAD

**Issue by LuckyRosy** [SecUSo/privacy-friendly-pedometer#52]
Step Counting is not update while walking with application open mode.and compare with other apps steps are not accurate.counting is updated in background only #3

**Comment by davidhedlund** [comment]
I walked 140 steps in one days says this app. It is broken, to fix it please inspect the code of a working Pedometer (no sensors required): https://f-droid.org/packages/name.bagi.levente.pedometer/

**Comment by Yonjuni** [comment]
I had a brief look into it, but it uses sensors, see [here](https://github.com/bagilevi/android-pedometer/blob/master/src/name/bagi/levente/pedometer/StepDetector.java). 
Depending on the device and sensitivity setting not all steps are counted in Privacy Friendly Pedometer. Therefore, we recommend to try different sensivity settings.

Just one remark: Could you tell us your device and Android version? In case you don't wish to post it here, you find an email addresse [here](https://secuso.org/pfa) There is a big differences between different devices.

**Comment by davidhedlund** [comment]
@Yonjuni Thanks!
Device: Samsung Galaxy Express 2
Android: 4.4.2

**Comment by davidhedlund** [comment]
@Yonjuni How do I change the sensitivity level then?

**Comment by davidhedlund** [comment]
@Yonjuni I found it.

**Comment by LaxmanDroid** [comment]
@Yonjuni thanks for response. from @LuckyRosy
Device: Moto g
Android:5.1

**Comment by davidhedlund** [comment]
@LuckyRosy Can you please also give the developer your device and android version?

**Comment by Yonjuni** [comment]
I have looked up the devices. Both have to use the accelerometer for step detection. Thus, the sensitivity level in the settings is very important. Please, try out different sensitivity settings.

**Comment by LaxmanDroid** [comment]
yea when i tried with change the sensitivity settings to high it shows double number of steps compare with other pedometer apps count.when i tried with low it never counts the steps(0).and finally i changed back to normal it show some accurate steps near to other apps on playstore but not exactly.

**Comment by Yonjuni** [comment]
Integrated in next update.

**Comment by davidhedlund** [comment]
@Yonjuni Thank you!
