### ISSUE TITLE
Add a Sensitivity disclaimer pop-up at first run

### ISSUE THREAD

**Issue by davidhedlund** [SecUSo/privacy-friendly-pedometer#53]
Yonjuni [said](https://github.com/SecUSo/privacy-friendly-pedometer/issues/52#issuecomment-314758976)
> Depending on the device and sensitivity setting not all steps are counted in Privacy Friendly Pedometer. Therefore, we recommend to try different sensivity settings.

Please inform your users with a pop-up saying that the Settings -> General -> Sensitivity should be calibrated.

**Comment by Yonjuni** [comment]
We should add a slide to the tutorial. The tutorial will also be added to the navigation drawer.

**Comment by davidhedlund** [comment]
@Yonjuni Thats a very good idea.

**Comment by Yonjuni** [comment]
Included in the tutorial
