### ISSUE TITLE
Add ability to stop step counter temporary

### ISSUE THREAD

**Issue by un-logic** [SecUSo/privacy-friendly-pedometer#6]
It's really a must have feature, because most of devices keep registering vibrations during commute by transport, which has nothing to do with physical activities.
So there must be a pause/resume button or slider in UI that is easy to access on the go. I recommend to put it on a separate pane in between summary and detailed panes. 
To prevent erroneous triggering there must be confirmation dialog that will offer to options. 
 -1st is a button to ignore comand and close dialog. 
 -2nd is button to proceed. 
 -there should be a third control like a wheel of numbers to choose preset time intervals between reminder notifications that will suggest to resume counting, in case you have forgotten to turn it back on upon arrival.
Time presets should be configurable via settings and the set could look like: 10, 20, 30, 45, 60, 90, 120 minutes.
To represent status of inactivity in summary pane step counter during this period can be grayed out and/or icon with walking man changed to a sitting pose.
Also to visualize such a period of inactivity on plot it can be colored with gray.

**Comment by Yonjuni** [comment]
Thanks for the comment.
I like your ideas and they would be a good feature in our application. We will consider them when we prepare the next version of the app.

**Comment by Yonjuni** [comment]
The step counter can be deactivated in the settings under:
Settings > General > Permanent step counter

**Comment by un-logic** [comment]
Yeah, I'm aware of that. Try it and all the steps that I've made today will get thrown away! Also application will still keep counting steps until it go to background! This is totally undesirable. And looks like a bug too.
You're missing the point here, there must be __fast and easy access__ to a suspend/resume UI control located at main screen of application. Why? Because when on the run you don't have enough time to spend on a tap, swipe, tap and tap again. Otherwise you will be counting anything but physical activity, right?

**Comment by Yonjuni** [comment]
Switches in the notification and the app could integrate this feature.

**Comment by ywum7fhv0skqh07h** [comment]
Can the app respect user termination? If I swipe the app away, I expect the background service to restart. Currently the only way to restart the app + background service is to Force Stop from the App Info menu.

**Comment by Yonjuni** [comment]
@ywum7fhv0skqh07h Currently not (yet). But we're working on an improvement. 
You can switch off the counter in the settings, but then all walked steps for the day are discarded, too.

**Comment by Yonjuni** [comment]
Integrated in next update. (Button in toolbar)
