### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [SecUSo/privacy-friendly-pedometer#60]
Hi @SecUSo

I found [this app ](https://play.google.com/store/apps/details?id=com.driviodevs.pedometer) on the Google Play Store. This guy just took the source code, added some ads and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove the false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under GNU GPL v3 and this guy is violating it by distributing the app without distributing the source code;
* He is falsely claiming he made the app;
* Also tell them that this guy has done the same thing already with other apps. Probably this is worth mentioning. (I watch him)

**Comment by Poussinou** [comment]
There is also [this one](https://play.google.com/store/apps/details?id=net.hassandroid.pedo.meter.step.count)

**Comment by tobiasneidig** [comment]
Thanks for reporting - I want to add [this one](https://play.google.com/store/apps/details?id=net.hassandroid.saraha) to the list.

**Comment by Yonjuni** [comment]
It's interesting that all contain advertisement.

**Comment by Poussinou** [comment]
This kind of people must be huge free and open source supporters ^^

**Comment by Poussinou** [comment]
@secuso Hum I also found [this one](https://www.amazon.fr/Drivio-Developers-Pedometer-Weight-Coach/dp/B073Y58DK1/ref=sr_1_6?s=mobile-apps&ie=UTF8&qid=1502434866&sr=1-6) and [this one](https://www.amazon.fr/Dhurandhar-Apps-Compteur-d%C3%A9tape-podom%C3%A8tre/dp/B073BF8N9C/ref=sr_1_57?s=mobile-apps&ie=UTF8&qid=1502434866&sr=1-57) on the Amazon Store. You can report them [here](https://www.amazon.com/gp/help/reports/infringement).

**Comment by Poussinou** [comment]
If found [this](https://play.google.com/store/apps/details?id=com.appsforlife.Pedometer) and [this](https://play.google.com/store/apps/details?id=org.privacykm.secuso) on Google Play 👍

**Comment by Poussinou** [comment]
https://play.google.com/store/apps/details?id=org.logiicsolution.privacyfriendlyactivitytracker

**Comment by Poussinou** [comment]
Everything was taken down.
Please report any other copycat here in the future, if any...
