### ISSUE TITLE
it does not work well

### ISSUE THREAD

**Issue by Fergus-B** [SecUSo/privacy-friendly-pedometer#63]
huawei P10, Android 7, F-Droid installled, prozessor is not allowed to sleep
pedometer does not start automatically in the morning
when it starts, it forgot the counted steps after some minutes
when the screen is on, the app sometimes count steps
more often it doesn't count
one have to switch the date back and forth to see new counted steps
i am walking a defined distance and count my own steps - the app shows most of the time a totally different result
compared with samsung health the app shows only the half or two-thirds of health
in this case I trust health more, because I know the distances I am walking
what can i do?

**Comment by licaon-kter** [comment]
Same on Mate9, Oreo. I blame Huawei and their aggresive "optimizations" that freeze apps. :(

**Comment by sleep-yearning** [comment]
Closing this since it refers to much older app version and has not been mentioned since 5 years
