### ISSUE TITLE
LOGO

### ISSUE THREAD

**Issue by waqasanwar94** [SecUSo/privacy-friendly-pedometer#64]

**Comment by licaon-kter** [comment]
Is this some self-assigned utopian.io task that you did in the hopes of winning some crypto-currency?

**Comment by waqasanwar94** [comment]
yes and whats wrong in this if i work for you free and get some reward because you will approve my work  if you will like otherwise you can reject my request

**Comment by waqasanwar94** [comment]
Complains about?

**Comment by waqasanwar94** [comment]
if you want i can make the logo for you but if you do not agree with me and you do not need any new logo then you can close this discussion no worry Thank you for your quick response i appreciate you

**Comment by Yonjuni** [comment]
@waqasanwar94 Thanks for your offer :) Thanks also for mentioning me, but @petermayer is currently managing the repo.

**Comment by xDeathwing** [comment]
Hello @licaon-kter and @Yonjuni also @petermayer, I am writing to you as Community Manager at Utopian.io .

Our goal at Utopian.io is incentivizing and rewarding original and valuable contributions to open source projects such as yours. Unfortunately, the monetary rewards offered also attract some abuse, which we cannot control or prevent, but only discourage by banning the users that violate our term of use and community guidelines from Utopian services. The user in question has been permanently banned from Utopian.io services.

I sincerely apologize for any negative experience that may have resulted from the actions of users on behalf of Utopian. To correct that, I would like to invite you to contact me to learn how Utopian.io can reward YOUR own work contributing to open source and help you promote your project to contributors and potential users alike.

Sincerely,
Deathwing
Utopian Community Manager

**Comment by Yonjuni** [comment]
@xDeathwing Thanks for clarification :)
