### ISSUE TITLE
Daily count

### ISSUE THREAD

**Issue by robert-tee** [SecUSo/privacy-friendly-pedometer#66]
This app is great and work very well. Thank you. But I have noticed an issue: if I did a lot of steps near the end of the day, the morning after I found  the steps splitted between the new day and the day before. (i.e. yesterday 6/3/2018 I walked 14000 steps, until 11p.m., this morning I woke up with 1500 steps, for today, and 12500 for yesterday).

**Comment by robert-tee** [comment]
could be something in generateReports() method?

**Comment by goodjohnjr** [comment]
> This app is great and work very well. Thank you. But I have noticed an issue: if I did a lot of steps near the end of the day, the morning after I found the steps splitted between the new day and the day before. (i.e. yesterday 6/3/2018 I walked 14000 steps, until 11p.m., this morning I woke up with 1500 steps, for today, and 12500 for yesterday).

My brother has the same problem with the latest version of this app from F-Droid on a Moto G7 Play phone with Android 9.

We want to use this app, but this problem may prevent that; and so hopefully someone can fix this.

-John Jr

**Comment by petermayer** [comment]
Thanks for reporting, we will have a look at it.

**Comment by goodjohnjr** [comment]
> 
> 
> Thanks for reporting, we will have a look at it.

You are welcome, and thank you Petermayer.

-John Jr

**Comment by schlosser83** [comment]
> similar problem 
About 20000 steps walked, shown on screen
Then walked again - and not added anymore. - instead they got lost / reduced to about 13000 comparable to day before.
Next day correctly 0 steps.
Appears to be first issue, I recognized.
Ps : Where is the underlaying database stored ?

**Comment by sleep-yearning** [comment]
The issue with not allocating steps to the correct day should be solved by now, hence I am closing this. Feel free to reopen if you find something here to be unsolved.
