### ISSUE TITLE
Potential Compatibility Issue

### ISSUE THREAD

**Issue by ACID-AndroidCompatibilityIssuesDetector** [SecUSo/privacy-friendly-pedometer#71]
Hi,
I notice in class org/secuso/privacyfriendlyactivitytracker/activities/AppCompatPreferenceActivity.java you have overriden function `isValidFragment()`, which is added to the class android.preference.PreferenceActivity in API version = 19. (See this [link](https://developer.android.com/sdk/api_diff/19/changes/android.preference.PreferenceActivity)).

Class ColorSettingsActivity extends `AppCompatPreferenceActivity`, which  extends `android.preference.PreferenceActivity`.  If you put some important operation into this function, the program may not execute normally in API<19.

**Comment by Kamuno** [comment]
The function `isValidFragment()` is not overwritten in AppCompatPreferenceActivity.java but in PreferencesActivity.java#L188. Also this function is meant to be overwritten (See [https://developer.android.com/reference/android/preference/PreferenceActivity.html#isValidFragment(java.lang.String)](https://developer.android.com/reference/android/preference/PreferenceActivity.html#isValidFragment(java.lang.String)))
I don't see any compatibility issues here.
