### ISSUE TITLE
Crash at launch : divide by zero ?

### ISSUE THREAD

**Issue by tmarti2** [SecUSo/privacy-friendly-pedometer#72]
I wanted to disable step goal, and tried to put zero in the corresponding field, the app crashed instantly. Since I did, app crashes at launch. If it's not the issue I'll post more details about my Android version etc.

**Comment by sleep-yearning** [comment]
In my testing, the app did not crash with a step goal of 0 currently. I am closing this, because the version has changed a lot. 
If you further encounter problems with this, feel free to reopen!
