### ISSUE TITLE
distance is not correct

### ISSUE THREAD

**Issue by Mithrandirro** [SecUSo/privacy-friendly-pedometer#76]
Hi,
thanks for the app, I appreciate useful apps without the need of spreading data.
Today I made a walk of about 5 km. The app counted 1200 steps and 0,62 km.
Both is unlikely to be true.
One step is about 60 cm.  So for 5 km ist would have taken about 5300 steps.
I wonder, how you calculate distances when only have the settings "weight" and "sex".

**Comment by sijanec** [comment]
Weight and sex are for calories calculation as far as I know. Is there really no setting for step length?

**Comment by tobiasneidig** [comment]
Hi,

thanks for your feedback and app usage.
The walking distance is calculated based on the preferences set in walking modes.

To change the step size per walking mode go to settings -> walking modes -> choose your active walking mode and change the step length.

**Comment by morckx** [comment]
Answered.
