### ISSUE TITLE
v2.2 on Android: Incorrect date and time in CSV export

### ISSUE THREAD

**Issue by msq-ie** [SecUSo/privacy-friendly-pedometer#80]
Date and time in csv export is incorrect on Android - all records exported as 1970-01-01 01:00:00.
Also - the <begin> tag should not be there, I believe

![git03](https://user-images.githubusercontent.com/3123428/124595228-49182080-de50-11eb-8301-1d822a5d40a7.png)

**Comment by sleep-yearning** [comment]
Thanks for reporting! This function was merged from a pull request, so we have to look into the cause.

**Comment by Ythogtha** [comment]
This issue is still present.
Export of data is not usable...

**Comment by AngelAcheJota** [comment]
Could you please generate a release with this correction? It would be very useful. Thank you so much!!!

**Comment by AngelAcheJota** [comment]
Thank you very much for your 3.0.1 release!!!
