### ISSUE TITLE
Does not count steps

### ISSUE THREAD

**Issue by CalcProgrammer1** [SecUSo/privacy-friendly-pedometer#84]
I just installed LineageOS 17 on my Galaxy Note 8 and am trying to stick to FOSS apps where possible.  This app looked nice as a replacement to the proprietary step counter app I was using before.  Unfortunately, it doesn't track steps.  I can shake my phone or walk laps around the house with my phone in my pocket and it doesn't count a single step.  I got the app from F Droid.  I tried an older pedometer app from there and it counts steps fine.

**Comment by Kamuno** [comment]
Hello! We are aware of the issue and the release v2.4 should fix this problem. Can you try with this version? It always takes a bit of time before the version is published to the fDroid store.
I'm closing this issue for now. If it still persists with version v2.4.. please don't hesitate to reopen it. Thank you!
