### ISSUE TITLE
v2.4 on Android - stopped counting again

### ISSUE THREAD

**Issue by msq-ie** [SecUSo/privacy-friendly-pedometer#85]
I'm on v2.4 on Android. It worked after the upgrade but suddenly stopped working today without my intervention.

I'm going back to stable 1.0.5 and will wait there until the 2.x matures.

**Comment by a1ad** [comment]
Yup, same here

**Comment by k5e** [comment]
Also here. It collects only a few steps even on an hour long walk that usually yields like 5000 steps.
Moto G 6+, Android 9

**Comment by 09F911029D74E35BD84156C5635688C0** [comment]
Same here. App wouldn't let me downgrade so had to back up db and uninstall first. Added in a couple hundred steps it missed since updating. Android 11.

**Comment by SentineI** [comment]
I just re-upgraded from 1.0.5 to 2.4, but cannot get it to count more than a few steps.  H/w counting not work at all.  S/w is very unreliable no matter the sensitivity, even with number of steps before start counting set to 1.  Going back to 1.0.5 again.

**Comment by msq-ie** [comment]
@Kamuno - is there any chance we could have beta version available via Play Store and / or F Droid in a way we can have both versions installed, side by side? I will be more than happy to test it on my mobile and report issues.

Right now every upgrade to 2.x and then rollback to 1.0.5 means a data loss for me. Thank you.

**Comment by k5e** [comment]
> Also here. It collects only a few steps even on an hour long walk that usually yields like 5000 steps.
> Moto G 6+, Android 9

Apparently, operation is back to normal on my device.
Thanks!

**Comment by k5e** [comment]
> > Also here. It collects only a few steps even on an hour long walk that usually yields like 5000 steps.
> > Moto G 6+, Android 9
> 
> Apparently, operation is back to normal on my device.
> Thanks!

Well, no.

Yesterday it counted 100 steps while I was on a walk and today it counted 4100 steps while the phone was on the desk. Strange.

**Comment by notzed** [comment]
I've had no luck since 1.0.5 either - that was super reliable.  2.2 didn't work at all and 2.4 isn't much better so I had to delete it.

I just now built and installed the latest version and did some trials.  Accelerometer mode doesn't work at all, hardware counter works only while the app is active and visible, and stops working forever after that until it's forced-stop or re-installed.

I notice that 1.0.5 only has services/HardwareStepDetectorService but 2.4 uses services/HardwareStepCounterService which is very different.  I suppose it's some logic to have it not run continuously but it looks pretty strange.

**Comment by CyberScooby** [comment]
I just tried your application (version 2.4) and it won't count a single step. I tried every combination of settings that were possible with no change. The only thing it currently does is drain the battery quickly.

Based on earlier comments I managed to locate version 1.0.5. Did a quick test and it is counting steps and thus far seems very accurate.

I am currently using a Samsung SM-G965W which is running Android 9

**Comment by RufioHugo** [comment]
Any progress at this thread?

jm2c ... can't we combine:
- https://github.com/SecUSo/privacy-friendly-pedometer/issues/79
- https://github.com/SecUSo/privacy-friendly-pedometer/issues/83
- https://github.com/SecUSo/privacy-friendly-pedometer/issues/84
- https://github.com/SecUSo/privacy-friendly-pedometer/issues/85
- https://github.com/SecUSo/privacy-friendly-pedometer/issues/89
All are the same well(?) known issue ... %-|

**Comment by lolilolicon** [comment]
I too have reverted to v1.0.5.

I my case, v2.4 behaves like this: I have `Use phone's step counting hardware` enabled. Let's say the steps start out being counted. Now, as soon as the phone locks, step counting stops. Then even after I unlock the phone, no new steps are counted; only when I tap the pause button at the top-right corner & then tap it (now a start button) again does it start counting again—until the phone locks... & rinse, lather, repeat.

**Comment by sleep-yearning** [comment]
Does this happen with the newest version 3.0.1 still?

**Comment by morckx** [comment]
Should be resolved already by #111
