### ISSUE TITLE
Icon is a bit awkward on /e/OS

### ISSUE THREAD

**Issue by wout** [SecUSo/privacy-friendly-pedometer#90]
I love this app. Only one minor detail, the icon looks very sloppy on /e/OS:

![image](https://user-images.githubusercontent.com/107324/129782231-02277979-28d1-4603-ae01-c7ef50cf3f2e.png)

**Comment by sleep-yearning** [comment]
I think the icon changed since then, possibly resolving this. 
Can you confirm?

**Comment by wout** [comment]
Yeah, it's fiexed. Thanks!
