### ISSUE TITLE
F-Droid page for this app links to out of date changelog

### ISSUE THREAD

**Issue by VeeEM** [SecUSo/privacy-friendly-pedometer#91]
The changelog link on [F-Droid](https://f-droid.org/en/packages/org.secuso.privacyfriendlyactivitytracker/) points to out of date changelog at https://github.com/SecUSo/privacy-friendly-pedometer/blob/HEAD/CHANGELOG.md

**Comment by sleep-yearning** [comment]
Thank you for the hint, the changelog is up to date now
