### ISSUE TITLE
Import from backup app currently not working correctly

### ISSUE THREAD

**Issue by Kamuno** [SecUSo/privacy-friendly-pedometer#96]

**Comment by Ythogtha** [comment]
Isn't it linked to [issue#80](https://github.com/SecUSo/privacy-friendly-pedometer/issues/80) ?
If dates are badly exported, the CSV file obviously can't be reimported.

**Comment by sleep-yearning** [comment]
This should be tested again since issue 80 is resolved by now

**Comment by morckx** [comment]
Resolved via https://github.com/SecUSo/privacy-friendly-pedometer/commit/225590ee5747a19fbb1d8954e795e43cc3554f68
