### ISSUE TITLE
Daily steps counted different in daily and weekly

### ISSUE THREAD

**Issue by rimugu** [SecUSo/privacy-friendly-pedometer#97]
The daily screen show I have walked 444 steps (unlikely)
The weekly screen shows (just for today) that I have walked 3,389 steps (most likely)
![20211111_153339](https://user-images.githubusercontent.com/3810662/141390730-edc8522c-330e-4525-bcd2-75d2bb525258.png)
![20211111_153331](https://user-images.githubusercontent.com/3810662/141390732-4e6b8aee-d242-45fc-8d0d-82deac092df1.png)
)

**Comment by sleep-yearning** [comment]
Thank you for the report. 
I would like to know if this stays consistently like that or do those values change at a later time?

**Comment by morckx** [comment]
Should be resolves by #111
