### ISSUE TITLE
Release a new Git tag

### ISSUE THREAD

**Issue by schra** [SecUSo/privacy-friendly-pedometer#99]
Could you please release a new Git tag for v2.5, @sleep-yearning? The F-droid update process waits for a new Git tag, see https://gitlab.com/fdroid/fdroiddata/-/blob/c65f774a2d526b6d775f2e072c07f30926f9d003/metadata/org.secuso.privacyfriendlyactivitytracker.yml#L85

**Comment by sleep-yearning** [comment]
We would love to do that but need to fix some bugs first.

**Comment by sleep-yearning** [comment]
Closing because the newest version is on F-Droid now
